framework:
  website: srfnstack.github.io/spliffy/
  github: SRFNStack/spliffy
  version: 1.0
  engines:
    - uwebsockets
language:
  engines:
    uwebsockets:
      files:
        - app.js
        - package.json
        - www/
