framework:
  github: luoxiaojun1992/sw-fw-less
  version: preview

  engines:
    - swoole

  modules:
    - sodium
    - bcmath
    - sockets

  environment:
    CFLAGS: "$CFLAGS -D_GNU_SOURCE"

  deps:
    - libsodium-dev

  command: php start.php
