framework:
  github: itsumura-h/nim-basolato
  version: 0.14

deps:
  - gcc
  - musl-dev
  - bsd-compat-headers
  - openssl
  - openssh-client
  - pcre-dev

build_opts: "-d:ssl --threads:on --threadAnalysis:off --gc:orc --putenv:PORT=3000"

build_command: "ducere build -p 3000"

custom_files:
  - main
  - startServer.sh
  - .env

command: "./startServer.sh"
