require:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - Rakefile

Style/Documentation:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - ruby/rack-routing/app/route_handler.rb
