framework:
  github: chubbyts/chubbyts-framework
  version: 1.6

  bootstrap:
    - npm -g install typescript
    - npm install
    - tsc

  files:
    - app.ts
    - package.json
    - tsconfig.json
