framework:
  github: chubbyts/chubbyts-framework
  version: 1.3

  engines:
    - node
    - uwebsockets

  bootstrap:
    - npm install
    - npm -g install typescript
    - tsc

  files:
    - app.ts
    - package.json
    - tsconfig.json
