language:
  version: 11

  files:
    - Makefile
    - "**/*.h"
    - "**/*.c"
    - "**/*.conf"

  static_files:
    - "**/*.conf"

  engines:
    default:
      command: /opt/web/simple

framework:
  engines:
    - default
