framework:
  github: walkor/Workerman
  version: 4.0

  engines:
    - workerman

environment:
  CFLAGS: "$CFLAGS -D_GNU_SOURCE"

php_mod:
  - pcntl
  - sockets

php_ext:
  - event

command: php start.php start
