framework:
  website: nestjs.com
  version: 9.3

  files:
    - nest-cli.json
    - src
    - tsconfig.build.json
    - tsconfig.json
    - package.json

  bootstrap:
    - npm -g install @nestjs/cli
    - nest build
