framework:
  github: sanic-org/sanic
  version: 22.6

  engines:
    - sanic
    - gunicorn
    - uvicorn
    - hypercorn

language:
  engines:
    sanic:
      command: python server.py
    gunicorn:
      environment:
        WORKER_CLASS: uvicorn.workers.UvicornWorker
      bootstrap:
        - pip install uvicorn
        - pip install gunicorn
