provider:
  default:
    language: 8.1

framework:
  github: bearframework/bearframework
  version: "1.10"

language:
  engines:
    php-fpm:
      modules:
        - gd

      build_deps:
        - libpng-dev
