framework:
  website: doc.networknt.com
  version: 2.1

  build:
    - mvn clean package -Prelease

  static_files:
    - target/benchmark-1.0.0.jar

  files:
    - build.gradle

  command: >
    /usr/bin/java
    -XX:+UseNUMA -XX:+UseParallelGC 
    -jar target/benchmark-1.0.0.jar
