framework:
  website: masoniteproject.com
  version: 4.16

  engines:
    - gunicorn
    - uwsgi
    - waitress

  build_deps:
    - libffi-dev
    - libssl-dev
    - curl

  bootstrap:
    - curl https://sh.rustup.rs > init.sh
    - sh init.sh -y
    - find $HOME/.cargo/bin -type f -exec install {} /usr/local/bin \;
    - rustup default nightly

language:
  engines:
    gunicorn:
      environment:
        PYTHON_APP: wsgi:application
    uwsgi:
      environment:
        PYTHON_APP: wsgi:application
    waitress:
      environment:
        PYTHON_APP: wsgi:application
