framework:
  website: lumen.laravel.com
  version: 9.0

  engines:
    - php-fpm
    - swoole

  files:
    - artisan
    - .swoole/config/laravels.php
    - .swoole/bin/laravels

language:
  engines:
    swoole:
      modules:
        - pcntl
      bootstrap:
        - mkdir storage
      command: php bin/laravels start
