language:
  version: 17
  engines:
    default:
      command: java -server -XX:+UseNUMA -XX:+UseParallelGC -XX:+AlwaysPreTouch -jar /usr/src/app/build/libs/server.jar

  files:
    - src/**/*.java
    - pom.xml

  files:
    - src/**/*.properties
    - src/**/*.xml
    - src/**/*.jsp

  fix:
    - ln -sfv /usr/local/openjdk-17/bin/java /usr/bin/java

  binaries:
    - target/benchmark-1.0.0.jar

  deps:
    - java-17-openjdk

  command: >
    /usr/bin/java
    -XX:+UseNUMA -XX:+UseParallelGC 
    -jar /opt/web/target/benchmark-1.0.0.jar
