framework:
  website: luminusweb.com
  version: 4.49

  image: clojure:temurin-17-lein

  build:
    - lein uberjar

  binaries:
    - target/uberjar/luminus.jar

  command: java -jar target/uberjar/luminus.jar 3000
