framework:
  website: emmett.sh
  version: 2.4

  engines:
    - uvicorn
    - gunicorn

  build_deps:
    - libffi-dev
    - libssl-dev

language:
  engines:
    gunicorn:
      environment:
        WORKER_CLASS: emmett.asgi.workers.EmmettWorker
    uvicorn:
      command: emmett serve --host 0.0.0.0 --port 3000 --workers $(nproc)
