framework:
  github: spiral/framework
  version: 3.7

  engines:
    - road-runner

  bootstrap:
    - vendor/bin/spiral get
    - php public/index.php configure

language:
  engines:
    road-runner:
      command: ./rr serve
