framework:
  github: spiral/framework
  version: 2.12

  files:
    - .rr.yaml

  engines:
    - road-runner

  bootstrap:
    - vendor/bin/spiral get
    - php public/index.php configure

  command: ./spiral serve
