framework:
  github: spiral/framework
  version: 2.14

  engines:
    - road-runner

  bootstrap:
    - vendor/bin/spiral get
    - php public/index.php configure

language:
  engines:
    road-runner:
      command: ./spiral serve
