framework:
  website: nestjs.com
  version: 9.2

  bootstrap:
    - npm install # workaround
    - npm --location=global install @nestjs/cli
    - nest build

  files:
    - nest-cli.json
    - src
    - tsconfig.build.json
    - tsconfig.json
    - package.json

  command: pm2-runtime start dist/app.js -i $(nproc)
