language:
  version: "1.20"

  engines:
    net-http:
      command: cd /go/bin && ./app
    fasthttp:
      command: cd /go/bin && ./app

framework:
  engines:
    - net-http

  files:
    - "**/*.go"
    - go.mod
