language:
  version: 8.1

framework:
  github: lizhichao/one
  version: 2.3

  engines:
    - swoole-4.8.x

  modules:
    - bcmath

language:
  engines:
    swoole:
      command: php App/swoole.php
    php-fpm:
      bootstrap:
        - mkdir -p App/RunCache
        - chmod 777 App/RunCache
