language:
  version: 1.7

  files:
    - "**/*.gradle"
    - "**/*.kts"
    - "**/*.kt"

  engines:
    default:
      command: java -server -XX:+UseNUMA -XX:+UseParallelGC -XX:+AlwaysPreTouch -jar /usr/src/app/build/libs/server.jar

framework:
  engines:
    - default
