framework:
  github: fomo-framework/fomo
  version: 2.0

  engines:
    - swoole

  extensions:
    - redis
    - pcntl

  bootstrap:
    - mkdir storage/logs -p

  command: php engineer server:start
